MODEL:
  YOLOV8_FOLDER: 'D:/Data/models/yolov8'
  YOLOV8_WEIGHTS: 'yolov8x_cf_v3'
  YOLOV9_FOLDER: 'D:/Data/models/yolov9'
  YOLOV9_WEIGHTS: 'yolov9e'
  RTDETR_FOLDER: 'D:/Data/models/rt-detr'
  RTDETR_WEIGHTS: 'rtdetr-l'
INPUT:
  FOLDER: 'D:/Data/CCT_Drones/P2_50'
  SOURCE: 'P2_50_100_CR.mp4'
DETECTION:
  CLASS_FILTER: [0,1,2,3,4,5,6]
  IMAGE_SIZE: 640
  CONFIDENCE: 0.5
  NUMBER: 100
SHOW: True
