YOLO:
  YOLO_WEIGHTS: 'yolov8m'
INPUT:
  FOLDER: 'D:/Data/'
  SOURCE: 'CHICO1_1.mp4'
DETECTION:
  CLASS_FILTER: [0,1,2,3,5,7]
  CONFIDENCE: 0.2
  IMAGE_SIZE: 1280
DRAW:
  LABELS: True
  BOXES: True
  MASKS: True
  TRACKS: True
  HEATMAP: True
  TRACK_LENGTH: 100
SHOW: True
SAVE:
  VIDEO: True
  CSV: True
  