MODEL:
  YOLOV8_FOLDER: 'D:/Data/models/yolov8'
  YOLOV8_WEIGHTS: 'yolov8x'
  NAS_WEIGHTS: 'yolo_nas_m'
  RTDETR_FOLDER: 'D:/Data/models/rt-detr'
  RTDETR_WEIGHTS: 'rtdetr-l'
INPUT:
  FOLDER: 'D:/Data'
  SOURCE: 'test_image.jpg'
DETECTION:
  CLASS_FILTER: [7]
  CONFIDENCE: 0.1
  IMAGE_SIZE: 640
TRACKING: True
DRAW:
  LABELS: True
  BOXES: True
  MASKS: False
SHOW: True
SAVE:
  IMAGE: True
  CSV: True
  