MODEL:
  YOLOV8_FOLDER: 'D:/Data/models/yolov8'
  YOLOV8_WEIGHTS: 'yolov8m'
INPUT:
  FOLDER: 'D:/Data'
  SOURCE: 0
DETECTION:
  CONFIDENCE: 0.2
  IMAGE_SIZE: 640
DRAW:
  CIRCLES: True
  LINES: True
  LABELS: True
SHOW: True
SAVE:
  VIDEO: True
  CSV: True
  SOURCE: True
