MODEL:
  YOLOV8_FOLDER: 'D:/Data/models/yolov8'
  YOLOV8_WEIGHTS: 'yolov8x_dr_v4'
  YOLOV9_FOLDER: 'D:/Data/models/yolov9'
  YOLOV9_WEIGHTS: 'yolov9e'
  RTDETR_FOLDER: 'D:/Data/models/rt-detr'
  RTDETR_WEIGHTS: 'rtdetr-l'
INPUT:
  FOLDER: 'D:/Data/CCT_Drones'
  SOURCE: 'P2_50_100_CR.mp4'
  # FOLDER: 'D:/Data'
  # SOURCE: 'C3_detenido.mp4'
DETECTION:
  CLASS_FILTER: [0,1,2,3,4,5,6]
  IMAGE_SIZE: 640
  CONFIDENCE: 0.5
DRAW:
  LABELS: True
  BOXES: True
  MASKS: False
  TRACKS: True
  HEATMAP: False
  TRACK_LENGTH: 100
SHOW: True
SAVE:
  VIDEO: True
  CSV: True
  