MODEL:
  YOLOV8_FOLDER: 'D:/Data/models/yolov8'
  YOLOV8_WEIGHTS: 'yolov8x_cf_v3'
  YOLOV9_FOLDER: 'D:/Data/models/yolov9'
  YOLOV9_WEIGHTS: 'yolov9c_cf'
  RTDETR_FOLDER: 'D:/Data/models/rt-detr'
  RTDETR_WEIGHTS: 'rtdetr-l'
INPUT:
  # FOLDER: 'D:/Data/CCT_Drones/P2_50'
  # SOURCE: 'P2_50_100_CR.mp4'
  # FOLDER: 'D:/Data'
  # SOURCE: 'C3_detenido.mp4'
  # FOLDER: 'D:/Data'
  # SOURCE: 0
  # FOLDER: 'D:/Data/Gustavo/timelapse_5_30_a_5_38'
  # SOURCE: 'VID_20240409_173213_00_001.mp4'
  FOLDER: 'D:/Data/Gustavo/Video_corto_6_07_a_6_12'
  # SOURCE: 'VID_20240409_180957_00_003(1).mp4' 
  # SOURCE: 'VID_20240409_180957_00_003(2).mp4'
  SOURCE: 'VID_20240409_180957_00_003(3).mp4'
  # SOURCE: 'VID_20240409_180957_00_003(4).mp4'
DETECTION:
  CLASS_FILTER: [0,1,2,3,4,5,6]
  IMAGE_SIZE: 640
  CONFIDENCE: 0.5
CALIBRATION:
  LENGTH: 75
  WIDTH: 25
DRAW:
  LABELS: True
  BOXES: True
  MASKS: False
  TRACKS: True
  HEATMAP: False
  TRACK_LENGTH: 100
SHOW: True
SAVE:
  VIDEO: True
  CSV: True
  SOURCE: False
  